package example

// Code generated by api2. DO NOT EDIT.

import (
	"context"

	"github.com/starius/api2"
)

type Client struct {
	api2client *api2.Client
}

var _ EchoService = (*Client)(nil)

func NewClient(baseURL string) *Client {
	routes := GetRoutes(nil)
	api2client := api2.NewClient(routes, baseURL)
	return &Client{
		api2client: api2client,
	}
}

func (c *Client) Hello(ctx context.Context, req *HelloRequest) (res *HelloResponse, err error) {
	res = &HelloResponse{}
	err = c.api2client.Call(ctx, res, req)
	if err != nil {
		return nil, err
	}
	return
}

func (c *Client) Echo(ctx context.Context, req *EchoRequest) (res *EchoResponse, err error) {
	res = &EchoResponse{}
	err = c.api2client.Call(ctx, res, req)
	if err != nil {
		return nil, err
	}
	return
}
