/* eslint-disable */
// prettier-disable
// prettier-ignore
// Code generated by api2. DO NOT EDIT.
import {route} from "./utils"

export const api = {
example: {
	IEchoService: {
			Hello: route<example.HelloRequest, example.HelloResponse>(
				"POST", "/hello",
				{"query":["key"]},
				{"header":["session"]}),
			Echo: route<example.EchoRequest, example.EchoResponse>(
				"POST", "/echo",
				{"header":["session"],"json":["text"]},
				{"json":["text"]}),
	},
},
}
 
export declare namespace example {

export type HelloRequest = { 
	key?: string 
}


export type HelloResponse = { 
	session?: string 
}


export type EchoRequest = { 
	session?: string  
	text: string 
}

// EchoResponse. 
export type EchoResponse = { 
	text: string // field comment. 
}


export type CustomType =  example.UserSettings & {
}


export type UserSettings = Record<string, any> |  null

export type CustomType2 =  example.UserSettings & {
}

}
