/* eslint-disable */
// prettier-disable
// prettier-ignore
// Code generated by api2. DO NOT EDIT.
import {route} from "./utils"

export const api = {
example: {
	IEchoService: {
			Hello: route<example.HelloRequest, example.HelloResponse>(
				"POST", "/hello",
				{"query":["key"]},
				{"header":["session"]}),
			Echo: route<example.EchoRequest, example.EchoResponse>(
				"POST", "/echo",
				{"header":["session"],"json":["text","dir"]},
				{"json":["text"]}),
	},
},
}
export enum DirectionEnum {
    East = 1,
    North = 0,
    South = 2,
    West = 3,
}

export declare namespace example {

export type HelloRequest = {
	key?: string
}


export type HelloResponse = {
	session?: string
}


export type EchoRequest = {
	session?: string
	text: string
	dir: example.Direction
}


export type Direction = `${DirectionEnum}`
// EchoResponse.
export type EchoResponse = {
	text: string // field comment.
}


export type CustomType =  example.UserSettings & {
}


export type UserSettings = Record<string, any> |  null

export type CustomType2 =  example.UserSettings & {
}

}
