/* eslint-disable */
// prettier-disable
// prettier-ignore
// Code generated by api2. DO NOT EDIT. 
export namespace example {

export type HelloRequest = { 
	Key: string 
}


export type HelloResponse = { 
	Session: string 
}


export type EchoRequest = { 
	Session: string  
	text: string 
}

// EchoResponse. 
export type EchoResponse = { 
	text: string // field comment. 
}


export type CustomType = { 
	Hell: number 
}

}
